### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by samanthacooper11** [pivotal-pez/admin-portal#4]
Trying to push the app against a PCF 1.7.10 fails throwing a memory address exception as detailed below.

```
ERR panic: runtime error: invalid memory address or nil pointer dereference
2016-08-25T11:45:19.34+0100 [APP/0]      ERR [signal 0xb code=0x1 addr=0x38 pc=0x4c2a2d]
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 16 [running]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR runtime.panic(0x785740, 0xa02333)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/xchapter7x/cloudcontroller-client.(*Client).createRequestData(0xc208054180, 0x0, 0x0, 0x7ed1b0, 0xa, 0x6d26c0, 0xc2080f23d0, 0x0, 0x0, 0xc2080f8380)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/xchapter7x/cloudcontroller-client/login.go:112 +0x47d
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/xchapter7x/cloudcontroller-client.(*Client).CreateRequest(0xc208054180, 0x7cd3d0, 0x3, 0x0, 0x0, 0x7ed1b0, 0xa, 0x6d26c0, 0xc2080f23d0, 0xc20807d760, ...)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/xchapter7x/cloudcontroller-client/login.go:77 +0x95
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/xchapter7x/cloudcontroller-client.(*Client).CreateAuthRequest(0xc208054180, 0x7cd3d0, 0x3, 0x0, 0x0, 0x7ed1b0, 0xa, 0x6d26c0, 0xc2080f23d0, 0x0, ...)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/xchapter7x/cloudcontroller-client/login.go:88 +0xb7
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/pivotal-pez/pezdispenser/cloudfoundryclient.(*RestRunner).Run(0xc20804f400)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/pivotal-pez/pezdispenser/cloudfoundryclient/rest_runner.go:17 +0x3fb
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/pivotal-pez/pezdispenser/cloudfoundryclient.(*CFClient).Query(0xc2080724b0, 0x7cd3d0, 0x3, 0x0, 0x0, 0x7ed1b0, 0xa, 0x6d26c0, 0xc2080f23d0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/pivotal-pez/pezdispenser/cloudfoundryclient/cf_client.go:65 +0x14b
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/pivotal-pez/admin-portal/events.(*EventSearch).CompileRecentEvents(0xc2080724e0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/events/eventsearch.go:22 +0x1ad
2016-08-25T11:45:19.34+0100 [APP/0]      ERR main.FetchEventsInfo(0xc2080540c0, 0xc208018960)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/main.go:109 +0x2a7
2016-08-25T11:45:19.34+0100 [APP/0]      ERR main.func·005()
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/main.go:88 +0x35
2016-08-25T11:45:19.34+0100 [APP/0]      ERR reflect.Value.call(0x6d3bc0, 0xc20803f020, 0x0, 0x130, 0x7cb890, 0x4, 0xa09ec8, 0x0, 0x0, 0x0, ...)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/reflect/value.go:563 +0x1210
2016-08-25T11:45:19.34+0100 [APP/0]      ERR reflect.Value.Call(0x6d3bc0, 0xc20803f020, 0x0, 0x130, 0xa09ec8, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/reflect/value.go:411 +0xd7
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/jasonlvhit/gocron.(*Job).run(0xc20804e300, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/jasonlvhit/gocron/gocron.go:91 +0x42a
2016-08-25T11:45:19.34+0100 [APP/0]      ERR github.com/jasonlvhit/gocron.(*Scheduler).RunAll(0xc2080c8000)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/Godeps/_workspace/src/github.com/jasonlvhit/gocron/gocron.go:418 +0x55
2016-08-25T11:45:19.34+0100 [APP/0]      ERR main.main()
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /gopath/src/github.com/pivotal-pez/admin-portal/main.go:96 +0x744
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 19 [finalizer wait]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR runtime.park(0x415ef0, 0xa09430, 0xa06ec9)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
2016-08-25T11:45:19.34+0100 [APP/0]      ERR runtime.parkunlock(0xa09430, 0xa06ec9)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
2016-08-25T11:45:19.34+0100 [APP/0]      ERR runfinq()
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
2016-08-25T11:45:19.34+0100 [APP/0]      ERR runtime.goexit()
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/proc.c:1445
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 23 [runnable]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net/http.(*persistConn).readLoop(0xc20808c000)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:868 +0x829
2016-08-25T11:45:19.34+0100 [APP/0]      ERR created by net/http.(*Transport).dialConn
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 17 [syscall]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR runtime.goexit()
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/proc.c:1445
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 24 [select]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net/http.(*persistConn).writeLoop(0xc20808c000)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
2016-08-25T11:45:19.34+0100 [APP/0]      ERR created by net/http.(*Transport).dialConn
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 27 [IO wait]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net.runtime_pollWait(0x7fcd17df8b48, 0x72, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net.(*pollDesc).Wait(0xc208029720, 0x72, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net.(*pollDesc).WaitRead(0xc208029720, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net.(*netFD).Read(0xc2080296c0, 0xc20803dc00, 0x400, 0x400, 0x0, 0x7fcd17df7418, 0xb)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net.(*conn).Read(0xc20803a118, 0xc20803dc00, 0x400, 0x400, 0x0, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/net.go:122 +0xe7
2016-08-25T11:45:19.34+0100 [APP/0]      ERR crypto/tls.(*block).readFromUntil(0xc2080729c0, 0x7fcd17df8cd0, 0xc20803a118, 0x5, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/crypto/tls/conn.go:451 +0xd9
2016-08-25T11:45:19.34+0100 [APP/0]      ERR crypto/tls.(*Conn).readRecord(0xc208088580, 0x17, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/crypto/tls/conn.go:536 +0x1ff
2016-08-25T11:45:19.34+0100 [APP/0]      ERR crypto/tls.(*Conn).Read(0xc208088580, 0xc2080f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/crypto/tls/conn.go:901 +0x16a
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net/http.noteEOFReader.Read(0x7fcd17df90d8, 0xc208088580, 0xc20808c5d8, 0xc2080f6000, 0x1000, 0x1000, 0xa2f000, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:1203 +0x72
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net/http.(*noteEOFReader).Read(0xc20807d500, 0xc2080f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    <autogenerated>:124 +0xca
2016-08-25T11:45:19.34+0100 [APP/0]      ERR bufio.(*Reader).fill(0xc208005380)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
2016-08-25T11:45:19.34+0100 [APP/0]      ERR bufio.(*Reader).Peek(0xc208005380, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/bufio/bufio.go:132 +0x101
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net/http.(*persistConn).readLoop(0xc20808c580)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:782 +0x95
2016-08-25T11:45:19.34+0100 [APP/0]      ERR created by net/http.(*Transport).dialConn
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f
2016-08-25T11:45:19.34+0100 [APP/0]      ERR goroutine 28 [select]:
2016-08-25T11:45:19.34+0100 [APP/0]      ERR net/http.(*persistConn).writeLoop(0xc20808c580)
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
2016-08-25T11:45:19.34+0100 [APP/0]      ERR created by net/http.(*Transport).dialConn
2016-08-25T11:45:19.34+0100 [APP/0]      ERR    /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
```

**Comment by xchapter7x** [comment]
Looks like it's unable to connect to the cloud controller. Did you setup
the ups as detailed in the readme?

**Comment by samanthacooper11** [comment]
Thanks for coming back to me - I did yes, I created a CUPS using the UAA admin user

**Comment by samanthacooper11** [comment]
I got it working by using the domain only for the cf_base_uri
